/*
 * Copyright © 2013-2018 Metreeca srl. All rights reserved.
 *
 * This file is part of Metreeca.
 *
 * Metreeca is free software: you can redistribute it and/or modify it under the terms
 * of the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or(at your option) any later version.
 *
 * Metreeca is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Metreeca.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package com.metreeca.link;

import com.metreeca.spec.Spec;

import java.util.Optional;
import java.util.function.Consumer;

import static com.metreeca.spec.things._JSON.field;
import static com.metreeca.spec.things._JSON.object;


/**
 * Linked data resource handler.
 */
@FunctionalInterface public interface Handler {

	//// Shared Handlers ///////////////////////////////////////////////////////////////////////////////////////////////

	public static void refused(final Request request, final Response response) {
		if ( request.user().equals(Spec.none) ) {
			unauthorized(request, response);
		} else {
			forbidden(request, response);
		}
	}

	public static void unauthorized(final Request request, final Response response) {
		response.status(Response.Unauthorized).done(); // WWW-Authenticate header generated by wrappers
	}

	public static void forbidden(final Request request, final Response response) {
		response.status(Response.Forbidden).done();
	}


	//// JSON Error Report Factories ///////////////////////////////////////////////////////////////////////////////////

	public static Object error(final String error) {
		return object(field("error", error));
	}

	public static Object error(final String error, final Throwable cause) {
		return error(error, Optional.ofNullable(cause.getMessage()).orElseGet(cause::toString));
	}

	public static Object error(final String error, final Object cause) {
		return object(field("error", error), field("cause", cause));
	}


	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	public void handle(final Request request, final Response response);

	public default void exec(final Consumer<Request.Writer> source, final Consumer<Response.Reader> target) {

		if ( source == null ) {
			throw new NullPointerException("null source");
		}

		if ( target == null ) {
			throw new NullPointerException("null target");
		}

		source.accept(new Request.Writer(request -> handle(request, new Response(request, target))));
	}


	public default Handler wrap(final Wrapper wrapper) {

		if ( wrapper == null ) {
			throw new NullPointerException("null wrapper");
		}

		return wrapper.wrap(this);
	}

}
