/*
 * Copyright © 2013-2018 Metreeca srl. All rights reserved.
 *
 * This file is part of Metreeca.
 *
 * Metreeca is free software: you can redistribute it and/or modify it under the terms
 * of the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or(at your option) any later version.
 *
 * Metreeca is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Metreeca.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package com.metreeca.next;

import java.util.function.Consumer;
import java.util.function.Function;


/**
 * Lazy object source.
 *
 * Manages a lazy object generation pipeline.
 *
 * @param <T> the type of the generated object
 */
@FunctionalInterface public interface Lazy<T> {

	/**
	 * Generates the source object.
	 *
	 * @param consumer the target consumer for the generated object
	 */
	public void accept(final Consumer<T> consumer);


	/**
	 * Maps this lazy object source.
	 *
	 * @param mapper the object mapping function
	 * @param <R>    the type of the object returned by {@code mapper}
	 *
	 * @return a new lazy object source generating the object obtained by applying {@code mapper} to the object
	 * generated by this lazy object source
	 *
	 * @throws NullPointerException if {@code mapper} is {@code null}
	 */
	public default <R> Lazy<R> map(final Function<T, R> mapper) {

		if ( mapper == null ) {
			throw new NullPointerException("null mapper");
		}

		return consumer -> accept(t -> consumer.accept(mapper.apply(t)));
	}

}
