/*
 * Copyright © 2013-2018 Metreeca srl. All rights reserved.
 *
 * This file is part of Metreeca.
 *
 * Metreeca is free software: you can redistribute it and/or modify it under the terms
 * of the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or(at your option) any later version.
 *
 * Metreeca is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Metreeca.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package com.metreeca.next;

import java.util.function.Consumer;
import java.util.function.Function;

import static java.util.Objects.requireNonNull;


/**
 * Lazy object origin.
 *
 * <p>Manages a lazy object processing pipeline.</p>
 *
 * @param <T> the type of the processed object
 */
@FunctionalInterface public interface Origin<T> {

	/**
	 * Connects a consumer to this origin.
	 *
	 * @param consumer the target object processor
	 */
	public void accept(final Consumer<T> consumer);


	/**
	 * Maps this lazy object origin.
	 *
	 * @param mapper the object mapping function
	 * @param <R>    the type of the object returned by {@code mapper}
	 *
	 * @return a new lazy object origin generating objects obtained by applying {@code mapper} to the objects
	 * generated by this lazy object origin
	 *
	 * @throws NullPointerException if {@code mapper} is {@code null}
	 */
	public default <R> Origin<R> map(final Function<T, R> mapper) {

		if ( mapper == null ) {
			throw new NullPointerException("null mapper");
		}

		return consumer -> accept(value -> consumer.accept(
				requireNonNull(mapper.apply(value), "null mapper return value"))
		);
	}

}
