/*
 * Copyright © 2013-2020 Metreeca srl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.metreeca.rest;

import java.util.function.Consumer;
import java.util.function.Function;

import static java.util.Objects.requireNonNull;


/**
 * Future value.
 *
 * <p>Wraps a lazily generated value.</p>
 *
 * @param <T> the type of the lazily generated value
 */
@FunctionalInterface public interface Future<T> {

	/**
	 * Creates a future value.
	 *
	 * @param value the value to be wrapped
	 * @param <T>   the type of the value to be wrapped
	 *
	 * @return a future value wrapping the supplied {@code value}
	 *
	 * @throws NullPointerException if {@code value} is null
	 */
	public static <T> Future<T> Value(final T value) {
		return consumer -> consumer.accept(value);
	}


	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	/**
	 * Maps this future value.
	 *
	 * @param mapper a value mapping function; must return a non-null value
	 *
	 * @return a new future value generating a value obtained by applying {@code mapper} to the value generated by this
	 * future value
	 *
	 * @throws NullPointerException if {@code mapper} is null or returns a null value
	 */
	public default Future<T> map(final Function<T, T> mapper) {

		if ( mapper == null ) {
			throw new NullPointerException("null mapper");
		}

		return consumer -> accept(value ->
				consumer.accept(requireNonNull(mapper.apply(value), "null mapper return value"))
		);
	}

	/**
	 * Maps this future value.
	 *
	 * @param mapper a value to future mapping function; must return a non-null value
	 * @param <R>    the type of the value lazily generated by {@code mapper}
	 *
	 * @return a new future value generating a value obtained by applying {@code mapper} to this future value
	 *
	 * @throws NullPointerException if {@code mapper} is null or returns a null value
	 */
	public default <R> Future<R> flatMap(final Function<T, Future<R>> mapper) {

		if ( mapper == null ) {
			throw new NullPointerException("null mapper");
		}

		return consumer -> accept(value ->
				requireNonNull(mapper.apply(value), "null mapper return value").accept(consumer)
		);
	}


	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	/**
	 * Connects a consumer to this future value.
	 *
	 * @param consumer the consumer for the lazily generated value
	 *
	 * @throws NullPointerException if {@code value} is null
	 */
	public void accept(final Consumer<T> consumer);

}
