/*
 * Copyright © 2013-2020 Metreeca srl. All rights reserved.
 *
 * This file is part of Metreeca/Link.
 *
 * Metreeca/Link is free software: you can redistribute it and/or modify it under the terms
 * of the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or(at your option) any later version.
 *
 * Metreeca/Link is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Metreeca/Link.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package com.metreeca.tree.shapes;

import com.metreeca.tree.Shape;
import com.metreeca.tree.probes.Traverser;

import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.stream.Stream;

import static com.metreeca.tree.shapes.All.all;
import static com.metreeca.tree.shapes.And.and;
import static java.util.Collections.emptyMap;
import static java.util.Collections.singletonMap;
import static java.util.stream.Collectors.*;


/**
 * Field structural constraint.
 *
 * <p>States that the derived focus set generated by following a single step path is consistent with a given {@link
 * Shape shape}.</p>
 */
public final class Field implements Shape {

	public static Field field(final Object name, final Object... values) {
		return new Field(name, all(values));
	}

	public static Field field(final Object name, final Shape... shapes) {
		return new Field(name, shapes.length == 1 ? shapes[0] : and(shapes));
	}


	public static Map<Object, Shape> fields(final Shape shape) {
		return shape == null ? emptyMap() : shape.map(new FieldProbe());
	}


	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	private final Object name;
	private final Shape shape;


	private Field(final Object name, final Shape shape) {

		if ( name == null ) {
			throw new NullPointerException("null name");
		}

		if ( shape == null ) {
			throw new NullPointerException("null shape");
		}

		this.name=name;
		this.shape=shape;
	}


	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	public Object getName() {
		return name;
	}

	public Shape getShape() {
		return shape;
	}


	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	@Override public <T> T map(final Probe<T> probe) {

		if ( probe == null ) {
			throw new NullPointerException("null probe");
		}

		return probe.probe(this);
	}


	@Override public boolean equals(final Object object) {
		return this == object || object instanceof Field
				&& name.equals(((Field)object).name)
				&& shape.equals(((Field)object).shape);
	}

	@Override public int hashCode() {
		return name.hashCode()^shape.hashCode();
	}

	@Override public String toString() {
		return "field("+name+(shape.equals(and()) ? "" : ", "+shape)+")";
	}


	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	private static final class FieldProbe extends Traverser<Map<Object, Shape>> {

		@Override public Map<Object, Shape> probe(final Shape shape) { return emptyMap();}


		@Override public Map<Object, Shape> probe(final Field field) {
			return singletonMap(field.getName(), field.getShape());
		}


		@Override public Map<Object, Shape> probe(final And and) {
			return fields(and.getShapes().stream());
		}

		@Override public Map<Object, Shape> probe(final Or or) {
			return fields(or.getShapes().stream());
		}

		@Override public Map<Object, Shape> probe(final When when) {
			return fields(Stream.of(when.getPass(), when.getFail()));
		}


		private Map<Object, Shape> fields(final Stream<Shape> stream) {
			return stream

					// collect name-to-shape mappings from nested shapes

					.flatMap(shape -> shape.map(this).entrySet().stream())

					// group by name, collect to a set of shapes and convert to an optimized conjunction

					.collect(groupingBy(Map.Entry::getKey, LinkedHashMap::new, mapping(Map.Entry::getValue,
							collectingAndThen(toCollection(LinkedHashSet::new), set ->
									set.size() == 1 ? set.iterator().next() : and(set))
					)));
		}

	}

}
